spring:
  application:
    name: product-service
  config:
    import: configserver:http://localhost:8888
    fail-fast: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082